### ISSUE TITLE
Release tracker issue

### ISSUE THREAD

**Issue by j-brendel** [rl-institut/SimBA#118]
- [x] Battery Efficiency in eBus-Toolbox config
- [x] Optimizer PR #109 @PaulScheerRLI 
- [x] RTD PR #117 (issue #25) @PaulScheerRLI @j-brendel 
- [x] Testing: #104 & #110 @stefansc1 @PaulScheerRLI 
- [x] Filter #92 : @lilAndy-bruh 
- [x] assign vehicles - eine Anpassung wirdf aktuell nicht angestrebt
- [x] Concistency check @PaulScheerRLI 
- [x] Errors and warnings: @stefansc1 -> #125 solves #90 & #101
- [x] update config checking
- [x] chained modes 
- [x] fix service optimization
- [x] name
- [x] logo
- [x] write new readme-md
- [x] make github public
- [x] publish rtd
- [x] activate new readme.md (with rtd link)
